### ISSUE TITLE
Completely non-interactive mode for running code

### ISSUE THREAD

**Issue by alchemyst** [SimonStreicher/FaultMap#14]
At the moment, my default entry-point for the code is `demo_all.py`. This pops up a window which I must close manually for all the code to run. We need a flag or a configuration option which kills all interaction and runs through the code without waiting for the user at all. This will make testing easier.

**Comment by SimonStreicher** [comment]
I believe the original problem has been fixed in the meantime. However, at the moment 'run_weigthcalc.py', 'run_noderank.py' and 'run_graphreduce.py' still need to be run separately, with some moving of files in-between. I will keep this open until the full workflow has been automated.

**Comment by SimonStreicher** [comment]
Currently, all running is non-interactive and no files need to be moved around for running a full analysis on a case. In order to generate all possible results for a specific case the following scripts need to be run in order:

`run_weightcalc.py`
`run_createarrays.py`
`run_trendextraction.py` (only for transient studies)
`run_noderank.py`
`run_graphreduce.py`

**Comment by SimonStreicher** [comment]
A single entry point is now available: `run_all.py`
